DROP TABLE IF EXISTS stats;

CREATE TABLE IF NOT EXISTS stats(
    id        BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    app       VARCHAR(100),
    uri       VARCHAR(100),
    ip        VARCHAR(100),
    timestamp TIMESTAMP WITHOUT TIME ZONE
);